package store

import (
	"database/sql"
	"errors"
	"fmt"
	"regexp"
	"strings"

	_ "github.com/duckdb/duckdb-go/v2"
)

type Store struct {
	db *sql.DB
}

// votes  — every recorded click. Upserted by (survey_id, voter).
// surveys — optional per-survey allowed-answer allowlist. Empty / row-absent
// means "open mode" (any slug-valid answer counts). Populated via the
// `make survey-create` target which writes through Quack with the same
// SURVEY_QUACK_TOKEN as `survey-reset`.
//
// The voter_name column supports per-survey named-voting mode. Default
// mode is "anonymous" (voter_name is empty string, not stored).
const schemaVotes = `
CREATE TABLE IF NOT EXISTS votes (
    ts        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    survey_id VARCHAR   NOT NULL,
    answer    VARCHAR   NOT NULL,
    voter     VARCHAR   NOT NULL,
    voter_name VARCHAR,
    PRIMARY KEY (survey_id, voter)
);
`

const schemaSurveys = `
CREATE TABLE IF NOT EXISTS surveys (
    survey_id       VARCHAR   PRIMARY KEY,
    allowed_answers VARCHAR   NOT NULL,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    mode            VARCHAR   DEFAULT 'anonymous'
);
`

// tokenSafe restricts the Quack token to URL-safe base64 chars so we can
// interpolate it into SQL without escaping. The token is generated by the
// operator (base64 of /dev/urandom), so this is purely a defence-in-depth check.
var tokenSafe = regexp.MustCompile(`^[A-Za-z0-9+/=_-]+$`)

func Open(path, quackAddr, quackToken string) (_ *Store, err error) {
	if quackAddr != "" {
		if !tokenSafe.MatchString(quackToken) {
			return nil, fmt.Errorf("SURVEY_QUACK_TOKEN must be URL-safe base64")
		}
	}

	db, err := sql.Open("duckdb", path)
	if err != nil {
		return nil, err
	}
	// Close the DB handle if Open fails after sql.Open succeeded — otherwise
	// the file lock on votes.duckdb leaks until process exit, which makes
	// crash-restart loops painful in dev.
	defer func() {
		if err != nil {
			db.Close()
		}
	}()
	// DuckDB has a single writer. Pin to one connection so writes and the
	// quack_serve call share the same session.
	db.SetMaxOpenConns(1)

	if _, err = db.Exec(schemaVotes); err != nil {
		return nil, fmt.Errorf("schema votes: %w", err)
	}
	if _, err = db.Exec(schemaSurveys); err != nil {
		return nil, fmt.Errorf("schema surveys: %w", err)
	}

	// Migrate existing tables: add columns if not present.
	// Safe to run on fresh databases (columns already exist from DDL above).
	if _, err = db.Exec(`ALTER TABLE votes ADD COLUMN IF NOT EXISTS voter_name VARCHAR`); err != nil {
		return nil, fmt.Errorf("migrate votes: %w", err)
	}
	if _, err = db.Exec(`ALTER TABLE surveys ADD COLUMN IF NOT EXISTS mode VARCHAR DEFAULT 'anonymous'`); err != nil {
		return nil, fmt.Errorf("migrate surveys: %w", err)
	}

	if quackAddr != "" {
		// Quack ships via the `core` extension repo from DuckDB 1.5.3 onwards.
		// Earlier versions (1.5.2 etc.) had it in `core_nightly` — this code
		// requires 1.5.3+, which is what duckdb-go-bindings/v2 v0.10503.x
		// bundles for linux/darwin/windows. The first `INSTALL` call needs
		// outbound HTTPS to extensions.duckdb.org to fetch the extension file.
		if _, err = db.Exec(`INSTALL quack`); err != nil {
			return nil, fmt.Errorf("install quack (need DuckDB 1.5.3+ and outbound HTTPS): %w", err)
		}
		if _, err = db.Exec(`LOAD quack`); err != nil {
			return nil, fmt.Errorf("load quack: %w", err)
		}

		// quack_serve takes named args via `=>`. The Go driver doesn't bind
		// named params, so we interpolate after validating both inputs above.
		quackURI := fmt.Sprintf("quack:%s", quackAddr)
		serveSQL := fmt.Sprintf(
			"CALL quack_serve('%s', token => '%s', allow_other_hostname => true)",
			quackURI, quackToken,
		)
		if _, err = db.Exec(serveSQL); err != nil {
			return nil, fmt.Errorf("quack_serve: %w", err)
		}
	}

	return &Store{db: db}, nil
}

func (s *Store) Close() error { return s.db.Close() }

// RecordVote records a vote for a survey answer. voterName is optional —
// pass "" for anonymous mode. If the voter has already voted, their answer
// is updated and the voter_name is updated to the new name if non-empty.
func (s *Store) RecordVote(surveyID, answer, voter, voterName string) error {
	// On conflict, set the timestamp with now() rather than relying on
	// excluded.ts. Using CURRENT_TIMESTAMP here trips DuckDB's binder
	// (it treats it as a column name in SET lists); now() works reliably.
	// COALESCE on voter_name means an empty name preserves the existing name.
	const q = `
        INSERT INTO votes (survey_id, answer, voter, voter_name) VALUES (?, ?, ?, ?)
        ON CONFLICT (survey_id, voter) DO UPDATE
        SET answer = excluded.answer, ts = now(), voter_name = COALESCE(excluded.voter_name, voter_name)
    `
	_, err := s.db.Exec(q, surveyID, answer, voter, voterName)
	return err
}

// Tally is one (answer, count) pair for a survey. Ordered most-popular-first.
type Tally struct {
	Answer string
	Clicks int
}

// GetSurveyAnswers returns the allowed answer slugs for a survey, in the
// order they were registered. nil means the survey is unregistered (open
// mode — any slug-valid answer counts). The landing page handler uses
// this slice form so it can render the buttons in a stable order.
func (s *Store) GetSurveyAnswers(surveyID string) ([]string, error) {
	var raw string
	err := s.db.QueryRow(
		`SELECT allowed_answers FROM surveys WHERE survey_id = ?`,
		surveyID,
	).Scan(&raw)
	if errors.Is(err, sql.ErrNoRows) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	var out []string
	for _, a := range strings.Split(raw, ",") {
		if a = strings.TrimSpace(a); a != "" {
			out = append(out, a)
		}
	}
	return out, nil
}

// GetAllowedAnswers returns the per-survey answer allowlist as a set for
// O(1) lookup from the vote hot-path. nil means the survey is not
// registered — the vote handler treats that as open mode.
func (s *Store) GetAllowedAnswers(surveyID string) (map[string]bool, error) {
	answers, err := s.GetSurveyAnswers(surveyID)
	if err != nil || answers == nil {
		return nil, err
	}
	out := make(map[string]bool, len(answers))
	for _, a := range answers {
		out[a] = true
	}
	return out, nil
}

// GetSurveyMode returns the voting mode for a survey: "anonymous" or "named".
// Unregistered surveys default to "anonymous". Pre-migration rows with a NULL
// mode value are also treated as "anonymous".
func (s *Store) GetSurveyMode(surveyID string) (string, error) {
	var mode string
	err := s.db.QueryRow(
		`SELECT mode FROM surveys WHERE survey_id = ?`,
		surveyID,
	).Scan(&mode)
	if errors.Is(err, sql.ErrNoRows) {
		return "anonymous", nil
	}
	if err != nil {
		return "anonymous", err
	}
	if mode == "" {
		return "anonymous", nil
	}
	return mode, nil
}

// UpsertSurvey creates or updates a survey's allowed-answers registration.
// If the survey_id already exists, the allowed_answers and mode are replaced.
// An empty mode string defaults to "anonymous".
func (s *Store) UpsertSurvey(surveyID, answers, mode string) error {
	if mode == "" {
		mode = "anonymous"
	}
	const q = `
		INSERT INTO surveys (survey_id, allowed_answers, mode)
		VALUES (?, ?, ?)
		ON CONFLICT (survey_id) DO UPDATE
		SET allowed_answers = excluded.allowed_answers, mode = excluded.mode
	`
	_, err := s.db.Exec(q, surveyID, answers, mode)
	return err
}

// ResetVotes deletes all votes for a given survey. The survey registration
// (allowed_answers) is preserved.
func (s *Store) ResetVotes(surveyID string) error {
	const q = `DELETE FROM votes WHERE survey_id = ?`
	_, err := s.db.Exec(q, surveyID)
	return err
}

// DeleteSurvey deletes all votes for a survey and then removes the survey
// registration itself. After this call the survey is fully gone. Both
// DELETEs happen in a single transaction for atomicity.
func (s *Store) DeleteSurvey(surveyID string) error {
	tx, err := s.db.Begin()
	if err != nil {
		return err
	}
	defer tx.Rollback()

	if _, err = tx.Exec(`DELETE FROM votes WHERE survey_id = ?`, surveyID); err != nil {
		return err
	}
	if _, err = tx.Exec(`DELETE FROM surveys WHERE survey_id = ?`, surveyID); err != nil {
		return err
	}
	return tx.Commit()
}

// TallyBySurvey returns the per-answer click count for a survey, most popular
// first. An unknown survey_id returns an empty slice (not an error) — the
// result page renders an "empty" state.
// VoteNames returns voter_name for each vote on a survey, keyed by voter
// hash. A vote recorded without a name will have an empty-string value.
// Returns an empty map (not nil) when the survey has no votes.
func (s *Store) VoteNames(surveyID string) (map[string]string, error) {
	rows, err := s.db.Query(
		`SELECT voter, COALESCE(voter_name, '') FROM votes WHERE survey_id = ?`,
		surveyID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	names := make(map[string]string)
	for rows.Next() {
		var voter, name string
		if err := rows.Scan(&voter, &name); err != nil {
			return nil, err
		}
		names[voter] = name
	}
	return names, rows.Err()
}

// VoteNamesByAnswer returns non-empty voter names grouped by answer for a survey.
// Names are sorted alphabetically within each answer. Returns an empty map for
// surveys with no votes or no named votes.
func (s *Store) VoteNamesByAnswer(surveyID string) (map[string][]string, error) {
	const q = `
		SELECT answer, voter_name
		FROM votes
		WHERE survey_id = ? AND voter_name IS NOT NULL AND voter_name != ''
		ORDER BY answer, voter_name
	`
	rows, err := s.db.Query(q, surveyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	out := make(map[string][]string)
	for rows.Next() {
		var answer, name string
		if err := rows.Scan(&answer, &name); err != nil {
			return nil, err
		}
		out[answer] = append(out[answer], name)
	}
	return out, rows.Err()
}

func (s *Store) TallyBySurvey(surveyID string) ([]Tally, error) {
	const q = `
		SELECT answer, count(*) AS clicks
		FROM votes
		WHERE survey_id = ?
		GROUP BY answer
		ORDER BY clicks DESC, answer
	`
	rows, err := s.db.Query(q, surveyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var out []Tally
	for rows.Next() {
		var t Tally
		if err := rows.Scan(&t.Answer, &t.Clicks); err != nil {
			return nil, err
		}
		out = append(out, t)
	}
	return out, rows.Err()
}
